# Generated by Django 2.1.5 on 2019-01-27 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('jobtype', models.CharField(db_index=True, max_length=32, verbose_name='jobtype')),
                ('comment', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MusicLink',
                'verbose_name_plural': 'MusicLinks',
            },
        ),
    ]
