# Generated by Django 2.1.5 on 2019-01-31 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiclink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, '喜歡'), (0, '不喜歡'), (-1, '這不是音樂！')], verbose_name='value')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create_at')),
                ('musiclink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_rating', to='musiclink.MusicLink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.AlterUniqueTogether(
            name='musicrating',
            unique_together={('user', 'musiclink')},
        ),
    ]
